EXTRN VAL1:WORD
EXTRN VAL2:WORD
EXTRN SUM:WORD
PUBLIC ADD_CARRY
.MODEL small
.CODE
ADD_CARRY  PROC FAR
           SUB BX,BX
		   MOV AX,VAL1
		   MOV DX,VAL2
		   ADD AX,DX
		   ADC BX,00
		   MOV SUM,AX
		   MOV SUM+2,BX
		   RET
ADD_CARRY  ENDP
           END