EXTRN ADD_CARRY: FAR
EXTRN MUL_CARRY: FAR
PUBLIC VAL1, VAL2, SUM, PRODUCT
.MODEL SMALL
.STACK 64
;-------------------------------------       
.DATA
VAL1 dw 2000
VAL2 dw 500
SUM dw ?
PRODUCT dw ?
;-------------------------------------
.CODE
MAIN PROC FAR
	MOV AX,@DATA
	MOV DS,AX
	
	CALL ADD_CARRY		;ADD VAL1 + VAL2 AND STORE IN SUM
	CALL MUL_CARRY		;MULTIPLY VAL1*VAL2 AND STORE IN PRODUCT
	
	 MOV AH,04Ch  ;RETURN TO DOS 
	 INT 21H
MAIN ENDP
     END  MAIN
