EXTRN VAL1:WORD
EXTRN VAL2:WORD
EXTRN PRODUCT:WORD
PUBLIC MUL_CARRY
.MODEL small
.CODE
MUL_CARRY    PROC   FAR
             MOV AX, VAL1
			 MOV CX, VAL2
			 MUL CX
			 MOV PRODUCT, AX
			 MOV PRODUCT+2, DX 
			 RET
MUL_CARRY   ENDP
            END 